//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESEIM.Models
{
    [Table("cms_items")]
    public class cms_items
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public int? cat_id { get; set; }
        public bool published { get; set; }
        public string intro_text { get; set; }
        public string full_text { get; set; }
        public string video { get; set; }
        public string gallery { get; set; }
        public string extra_fields { get; set; }
        public string extra_fields_search { get; set; }
        public DateTime? created { get; set; }
        public int? created_by { get; set; }
        public string created_by_alias { get; set; }
        public int? checked_out { get; set; }
        public DateTime? checked_out_time { get; set; }
        public DateTime? modified { get; set; }
        public int? modified_by { get; set; }
        public DateTime? publish_up { get; set; }
        public DateTime? publish_down { get; set; }
        public bool? trash { get; set; }
        public int? access { get; set; }
        public int? ordering { get; set; }
        public short? featured { get; set; }
        public int? featured_ordering { get; set; }
        public string image_caption { get; set; }
        public string image_credits { get; set; }
        public string video_caption { get; set; }
        public string video_credits { get; set; }
        public int? hits { get; set; }
        public string @params { get; set; }
        public string meta_desc { get; set; }
        public string meta_data { get; set; }
        public string meta_key { get; set; }
        public string plugins { get; set; }
        public string language { get; set; }
        public int? template { get; set; }
        public DateTime? date_post { get; set; }
    }
}
//namespace III.WebApp.Domain.DbContext
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class cms_items
//    {
//        public int id { get; set; }
//        public string title { get; set; }
//        public string alias { get; set; }
//        public Nullable<int> cat_id { get; set; }
//        public Nullable<bool> published { get; set; }
//        public string intro_text { get; set; }
//        public string full_text { get; set; }
//        public string video { get; set; }
//        public string gallery { get; set; }
//        public string extra_fields { get; set; }
//        public string extra_fields_search { get; set; }
//        public Nullable<System.DateTime> created { get; set; }
//        public Nullable<int> created_by { get; set; }
//        public string created_by_alias { get; set; }
//        public Nullable<int> checked_out { get; set; }
//        public Nullable<System.DateTime> checked_out_time { get; set; }
//        public Nullable<System.DateTime> modified { get; set; }
//        public Nullable<int> modified_by { get; set; }
//        public Nullable<System.DateTime> publish_up { get; set; }
//        public Nullable<System.DateTime> publish_down { get; set; }
//        public Nullable<bool> trash { get; set; }
//        public Nullable<int> access { get; set; }
//        public Nullable<int> ordering { get; set; }
//        public Nullable<short> featured { get; set; }
//        public Nullable<int> featured_ordering { get; set; }
//        public string image_caption { get; set; }
//        public string image_credits { get; set; }
//        public string video_caption { get; set; }
//        public string video_credits { get; set; }
//        public Nullable<int> hits { get; set; }
//        public string @params { get; set; }
//        public string meta_desc { get; set; }
//        public string meta_data { get; set; }
//        public string meta_key { get; set; }
//        public string plugins { get; set; }
//        public string language { get; set; }
//        public Nullable<int> template { get; set; }
//        public Nullable<System.DateTime> date_post { get; set; }
//    }
//}
