//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESEIM.Models
{
    [Table("cms_comments")]
    public class cms_comments
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        public int item_id { get; set; }
        public int? user_id { get; set; }
        public string user_name { get; set; }
        public DateTime? comment_date { get; set; }
        public string comment_text { get; set; }
        public string comment_email { get; set; }
        public string comment_url { get; set; }
        public bool? published { get; set; }
        public string comment_title { get; set; }
    }
}
//namespace III.WebApp.Domain.DbContext
//{
//    using System;
//    using System.Collections.Generic;
    
//    public partial class cms_comments
//    {
//        public int id { get; set; }
//        public int item_id { get; set; }
//        public Nullable<int> user_id { get; set; }
//        public string user_name { get; set; }
//        public Nullable<System.DateTime> comment_date { get; set; }
//        public string comment_text { get; set; }
//        public string comment_email { get; set; }
//        public string comment_url { get; set; }
//        public Nullable<bool> published { get; set; }
//        public string comment_title { get; set; }
//    }
//}
